new difference
djunehor/temp pull request #3
Opened 2020-10-27 12:53 UTC by djunehor

2020-10-27 13:54 UTC, harmydiano requested changes

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/ControllerGeneratorCommand.js
> +      fs.writeFile(Helpers.appRoot(`app/Controllers/Http/Admin/${pascalName}Controller.js`), data, function (err) {
This line is too long, you can place the folder path in a variable

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/ControllerGeneratorCommand.js
> +        vm.addRoutes({singular:singular, plural:plural, tableName:tableName, pascalName: pascalName});
You can actually write your object like this {singular, plurall} since the key and value are the same and the line is long as well

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/ControllerGeneratorCommand.js
> +  async generateString(data, {columnTypes, singular, tableName, pascalName}) {
The expected object params can be assigned into a single object then you can access each of them through its properties.

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/ControllerGeneratorCommand.js
> +    let columnsTypes = await tableColumns(tableName);
Is columnsTypes mutable? why did you use let? And why did you await?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/ControllerGeneratorCommand.js
> +      if(!columnsTypes[columnName]['primary']) {
Why did you access the object's property with []?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/ControllerGeneratorCommand.js
> +      if(!columnsTypes[columnName]['primary']) {
And why didn't you make the algorithm a function?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/ControllerGeneratorCommand.js
> +    Object.keys(columnsTypes).forEach(columnName => {
Why is the algorithm not a function? Why do you access the object's property with []?
Why did you use a switch case?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudGeneratorCommand.js
> +  async handle (args, options) {
What happens if options.connection  is false?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudGeneratorCommand.js
> +    execSync(`node ace crud:model ${tableName} ${options.connection ? `--connection=${options.connection}` : ``}`, (e, stdout, stderr) => {
Your code per line must not exceed 150 characters in length

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +const Env = use('Env');
Why did you start some variables with a small letter and another upper case

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +  async handle (args, options) {
Your function must only do one thing and be short. Avoid conditional statements.

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +        prefix.length > 20
Why did you hardcode the integers?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +        this.error('Prefix must be an alphanumeric string between 5 and 50 characters.');
Why did you hardcode the error response?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +  async handle (args, options) {
The function name is not descriptive enough for what it does.

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +    await this.copy(`${__dirname}/../templates/default/controller/ProfileController.js`, Helpers.appRoot('app/Controllers/Http/Admin/ProfileController.js'))
Too long

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +    await this.copy(`${__dirname}/../templates/RequestTypeMiddleware.js`, Helpers.appRoot('app/Middleware/RequestTypeMiddleware.js'))
Too long and why are you awaiting?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +    await this.copy(`${__dirname}/../templates/default/controller/ProfileController.js`, Helpers.appRoot('app/Controllers/Http/Admin/ProfileController.js'))
Why await?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +    await this.copy(`${__dirname}/../templates/default/views`, Helpers.viewsPath('admin'));
Why await?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +    for (let path of paths) {
Why is this not a function?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +    let baseUrl = `${Env.get('APP_URL')}/${Config.get('crudGenerator.admin_prefix')}`;
Why did you use let?

2020-10-27 13:54 UTC, harmydiano commented on src/Commands/CrudInitCommand.js
> +    let paths = [
Why let?

2020-10-27 13:57 UTC, harmydiano commented on src/Commands/ControllerGeneratorCommand.js
> +      data = await vm.generateString(data, {columnTypes:columnsTypes,singular:singular,tableName:tableName, pascalName: pascalName});
Why is generateString() an async function?
Give space between your object data.

2020-10-27 17:16 UTC, djunehor commented on src/Commands/ControllerGeneratorCommand.js
> +      data = await vm.generateString(data, {columnTypes:columnsTypes,singular:singular,tableName:tableName, pascalName: pascalName});
`generateString()` is an async function cos it calls an async method

2020-10-27 17:26 UTC, djunehor commented on src/Commands/ControllerGeneratorCommand.js
> +    let columnsTypes = await tableColumns(tableName);
`tableColumns()` is an async function (cos it performs DB queries)

2020-10-27 17:27 UTC, djunehor commented on src/Commands/CrudInitCommand.js
> +    await this.copy(`${__dirname}/../templates/default/controller/ProfileController.js`, Helpers.appRoot('app/Controllers/Http/Admin/ProfileController.js'))
`this.copy()` is an async file operation. The file needs to be in place for the next line to use

2020-10-27 17:28 UTC, djunehor commented on src/Commands/ControllerGeneratorCommand.js
> +  async generateString(data, {columnTypes, singular, tableName, pascalName}) {
I did it this way so the params are readable from the method definition

2020-10-27 17:35 UTC, djunehor commented on src/Commands/ControllerGeneratorCommand.js
> +      if(!columnsTypes[columnName]['primary']) {
It's just 3 lines and isn't used anywhere else. It's only relevant to the current method

2020-10-28 11:28 UTC, merged

2020-10-28 14:19 UTC, harmydiano commented on src/Commands/ControllerGeneratorCommand.js
> +    let columnsTypes = await tableColumns(tableName);
Okay